### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by joeworkman** [GeneaLabs/panic-nova-phpmd#2] opened 2021-07-01 16:42 UTC
I am getting this error when using your extension... 

```
Extension encountered an uncaught exception:
/Users/joeworkman/Library/Application Support/Nova/Extensions/genealabs.phpmd/Scripts/main.js (Line 240, Column 0)
TypeError: null is not an object (evaluating 'issue.message.match(/^.*? line: (.*?), col: .*$/i)[1]')
    file:///Users/joeworkman/Library/Application%20Support/Nova/Extensions/genealabs.phpmd/Scripts/main.js:240:84
    map@[native code]
    parseLinterOutput@file:///Users/joeworkman/Library/Application%20Support/Nova/Extensions/genealabs.phpmd/Scripts/main.js:228:21
    file:///Users/joeworkman/Library/Application%20Support/Nova/Extensions/genealabs.phpmd/Scripts/main.js:159:51

PHP Mess Detector issues may be reported at https://github.com/GeneaLabs/panic-nova-phpmd/issues
```

Could it be the deprecated messages?

![CleanShot 2021-07-01 at 09 42 20](https://user-images.githubusercontent.com/225628/124160053-aecf6b80-da50-11eb-87f5-c51be73f5cb0.jpg)

**Comment by mikebronner** [comment] 2021-07-01 17:33
Hi @joeworkman. thanks for writing in. I will try to fix this ASAP, been swamped at work. :) I would recommend temporarily disabling this extension, as it has crashed my Nova editor every time since version 7 was released.

Duplicate of #1

**Closed as completed by mikebronner** 2021-07-01 17:33 UTC

**Comment by mikebronner** [comment] 2021-07-01 18:27
@joeworkman Go ahead and give it a shot now. Release 0.1.17 should do the trick again. :) Let me know how it goes. Thanks again for reminding me about the issue.
